### PR TITLE
Bump version number in README

### PR DESCRIPTION
**Pull request by anthonator**

### CODE REVIEW

**Comment by sorentwo** [comment]
Thanks for this. I'll make this part of my release process.

**Comment by axelson** [comment]
If you want you could also make it into a test:
```
  test "README.md version is up to date" do
    app = :oban
    app_version = Application.spec(app, :vsn) |> to_string()
    readme = File.read!("README.md")
    [_, readme_version] = Regex.run(~r/{:#{app}, "(.+)"}/, readme)
    assert Version.match?(app_version, readme_version)
  end
```

**Comment by sorentwo** [comment]
@axelson Great suggestion. I ended up making it into a pre-commit hook 👍

**Comment by axelson** [comment]
Ah, that's pretty nifty

**Pull request merged**
