### PR TITLE
Added postgres 12.2 to test matrix

### PR DESCRIPTION
**Pull request by anthonator**

### CODE REVIEW

**Comment by anthonator** [comment]
You can check CI results here.

 https://github.com/anthonator/oban/actions/runs/48888188

**Comment by sorentwo** [comment]
Would you mind rebasing from master? It has an action change that is overwritten in this branch.

**Comment by anthonator** [comment]
I’m out but I can once I get back.

**Comment by anthonator** [comment]
Sorry for the commit junk but rebased as promised.

**Comment by sorentwo** [comment]
Don't sweat the commit junk, I squash it anyhow. Thanks again 💛

**Pull request merged**
