### PR TITLE
Fix links to guides in README

### PR DESCRIPTION
**Pull request by dsdshcym**

### CODE REVIEW

**Comment by sorentwo** [comment]
Thanks! 💛

**Comment by dsdshcym** [comment]
Ooops, I think this change might break the links in Hexdocs though 😱 
Maybe the fix is not this simple, we may need to make the way oban generates these Hexdocs pages consistent with their structure in the repo?

**Comment by sorentwo** [comment]
Ah. Yeah, the end goal is to minimize the readme and expand all sections into proper guides. When in doubt, favor the hexdocs version of the README version.

**Comment by dsdshcym** [comment]
yeah, that makes sense
I'm not sure if we can make github version work then
I think we'd better revert this PR to fix hexdocs version

**Comment by sorentwo** [comment]
Reverted 👍

**Pull request merged**
