### PR TITLE
Fixed Oban.Queue.Executor failure type

### PR DESCRIPTION
**Pull request by anthonator**

### CODE REVIEW

**Comment by anthonator** [comment]
I'm not sure why CI isn't running but you can check the results in my repo.

https://github.com/anthonator/oban/actions/runs/48846637

**Comment by sorentwo** [comment]
Thanks for the fix! I was trying to bundle it with a fix to dialyzer caching (which I believe you also had a thread about on the forum).

CI isn't running here because it is only set to `push`, not `[push, pull_request]`. I'll push a change after this is in 👍

**Comment by sorentwo** [comment]
Found it! Here is the comment I was referring to: https://elixirforum.com/t/caching-dialyzer-output-with-github-actions/27648/4?u=sorentwo

**Comment by anthonator** [comment]
Ah, nice!

Although there's a typo on that thread 😬

It should be `:plt_core_path` and not `:plt_cor_path`.

**Pull request merged**
